version: 0.2

env:
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  parameter-store:
    SSH_KEY: "/myproject/ansible-ssh-key"
    AWS_ACCESS_KEY_ID: "/myproject/aws-access-key-id"
    AWS_SECRET_ACCESS_KEY: "/myproject/aws-secret-access-key"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Ansible..."
      - pip install ansible
      - echo "Installing AWS CLI..."
      - pip install awscli

  pre_build:
    commands:
      - echo "Preparing SSH key..."
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo "SSH key is written to ~/.ssh/id_rsa"
      - echo "Configuring AWS CLI..."
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region us-west-2

  build:
    commands:
      - echo "Running Ansible playbook to configure EC2 instance..."
      - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini nginx-setup.yml
      - echo "Playbook execution completed"

  post_build:
    commands:
      - echo "Cleaning up..."
      - rm -f ~/.ssh/id_rsa
      - echo "Pipeline completed successfully!"

artifacts:
  files:
    - "**/*"
